server.port=8080
rest.path-host=localhost

spring.jms.enabled=true

# ActiveMQ Broker
message-queue.bind-address=tcp://${mq.listen.host:${rest.path-host}}:${mq.listen.port:7777}
message-queue.db-directory=${working.directory}/mq
message-queue.tmp-directory=${java.io.tmpdir}/mq

message-queue.flow-control-enabled=false
message-queue.max-inactivity-duration=0
message-queue.producer-window-size=1048576

# 32 MB per destination
message-queue.memory-limit=33554432
# 256 MB broker-wide heap
message-queue.memory-usage-limit=268435456
# 1 GB persistent store
message-queue.store-usage-limit=1073741824
# 100 MB temp store
message-queue.temp-usage-limit=104857600