# JMS Settings
spring.jms.pub-sub-domain=true

# Broker Settings
message-queue.broker-address=tcp://${mq.host:localhost:7777}

message-queue.flow-control-enabled=false
message-queue.max-inactivity-duration=0
message-queue.producer-window-size=1048576